ARG NODE_BASE_IMAGE=node:20-alpine
FROM ${NODE_BASE_IMAGE} AS builder

WORKDIR /app

# 安装依赖并编译
COPY resume-management/package*.json resume-management/jsconfig.json ./
COPY resume-management/ .
RUN npm install
RUN npm run build

FROM ${NODE_BASE_IMAGE} AS runner

WORKDIR /app
RUN npm install -g serve

COPY --from=builder /app/dist ./dist

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]

